### ISSUE TITLE
Error when building.

### ISSUE THREAD

**Issue by tokejepsen** [getavalon/docs#4]
When using ```. build_docker.sh```, I got the following error:

```bash
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7NGqNH/tornado/setup.py", line 146, in <module>
        raise ImportError("Tornado requires an up-to-date SSL module. This means "
    ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7NGqNH/tornado/
The command '/bin/sh -c wget https://bootstrap.pypa.io/get-pip.py &&    mayapy get-pip.py &&    mayapy -m pip install -r requirements.txt' returned a non-zero code: 1
```

**Comment by mottosso** [comment]
Looks like a problem coming from mkdocs.

- https://github.com/JuliaDocs/Documenter.jl/issues/659

Investigating..

**Comment by mottosso** [comment]
Fixed
